@startuml
!include style.puml
skinparam arrowThickness 1.1
skinparam arrowColor MODEL_COLOR
skinparam classBackgroundColor MODEL_COLOR

Class "<<interface>>\nIterable" as Iterable
Class UniqueTagList
Class Tag
Class DuplicateTagException
Class TagNotFoundException

UniqueTagList .up.|> Iterable
UniqueTagList *--> "*" Tag : internalList
UniqueTagList ..> DuplicateTagException : throws
UniqueTagList ..> TagNotFoundException : throws
@enduml
